package com.cn.ssm.entity;

import java.io.Serializable;

public class APPToken implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptoken.extime
     *
     * @mbggenerated
     */
    private Long extime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.id
     *
     * @return the value of apptoken.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.id
     *
     * @param id the value for apptoken.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptoken.extime
     *
     * @return the value of apptoken.extime
     *
     * @mbggenerated
     */
    public Long getExtime() {
        return extime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptoken.extime
     *
     * @param extime the value for apptoken.extime
     *
     * @mbggenerated
     */
    public void setExtime(Long extime) {
        this.extime = extime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        APPToken other = (APPToken) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getExtime() == null ? other.getExtime() == null : this.getExtime().equals(other.getExtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getExtime() == null) ? 0 : getExtime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", extime=").append(extime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}