package com.cn.ssm.entity;

import java.io.Serializable;
import java.util.Date;

public class Consumables implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumables.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumables.goods_ID
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumables.user_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumables.live_time
     *
     * @mbggenerated
     */
    private Date liveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consumables
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumables.ID
     *
     * @return the value of consumables.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumables.ID
     *
     * @param id the value for consumables.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumables.goods_ID
     *
     * @return the value of consumables.goods_ID
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumables.goods_ID
     *
     * @param goodsId the value for consumables.goods_ID
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumables.user_ID
     *
     * @return the value of consumables.user_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumables.user_ID
     *
     * @param userId the value for consumables.user_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumables.live_time
     *
     * @return the value of consumables.live_time
     *
     * @mbggenerated
     */
    public Date getLiveTime() {
        return liveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumables.live_time
     *
     * @param liveTime the value for consumables.live_time
     *
     * @mbggenerated
     */
    public void setLiveTime(Date liveTime) {
        this.liveTime = liveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Consumables other = (Consumables) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLiveTime() == null ? other.getLiveTime() == null : this.getLiveTime().equals(other.getLiveTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLiveTime() == null) ? 0 : getLiveTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", userId=").append(userId);
        sb.append(", liveTime=").append(liveTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}