package com.cn.ssm.entity;

import java.io.Serializable;

public class Friends implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.user_ID1
     *
     * @mbggenerated
     */
    private Integer userId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.user_ID2
     *
     * @mbggenerated
     */
    private Integer userId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friends
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.user_ID1
     *
     * @return the value of friends.user_ID1
     *
     * @mbggenerated
     */
    public Integer getUserId1() {
        return userId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.user_ID1
     *
     * @param userId1 the value for friends.user_ID1
     *
     * @mbggenerated
     */
    public void setUserId1(Integer userId1) {
        this.userId1 = userId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.user_ID2
     *
     * @return the value of friends.user_ID2
     *
     * @mbggenerated
     */
    public Integer getUserId2() {
        return userId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.user_ID2
     *
     * @param userId2 the value for friends.user_ID2
     *
     * @mbggenerated
     */
    public void setUserId2(Integer userId2) {
        this.userId2 = userId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Friends other = (Friends) that;
        return (this.getUserId1() == null ? other.getUserId1() == null : this.getUserId1().equals(other.getUserId1()))
            && (this.getUserId2() == null ? other.getUserId2() == null : this.getUserId2().equals(other.getUserId2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId1() == null) ? 0 : getUserId1().hashCode());
        result = prime * result + ((getUserId2() == null) ? 0 : getUserId2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId1=").append(userId1);
        sb.append(", userId2=").append(userId2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}