package com.cn.ssm.entity;

import java.io.Serializable;

public class Players implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.salary
     *
     * @mbggenerated
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.info_id
     *
     * @mbggenerated
     */
    private Integer infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.stats_ID
     *
     * @mbggenerated
     */
    private Integer statsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.team
     *
     * @mbggenerated
     */
    private String team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.contract
     *
     * @mbggenerated
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table players
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.ID
     *
     * @return the value of players.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.ID
     *
     * @param id the value for players.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.salary
     *
     * @return the value of players.salary
     *
     * @mbggenerated
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.salary
     *
     * @param salary the value for players.salary
     *
     * @mbggenerated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.info_id
     *
     * @return the value of players.info_id
     *
     * @mbggenerated
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.info_id
     *
     * @param infoId the value for players.info_id
     *
     * @mbggenerated
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.stats_ID
     *
     * @return the value of players.stats_ID
     *
     * @mbggenerated
     */
    public Integer getStatsId() {
        return statsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.stats_ID
     *
     * @param statsId the value for players.stats_ID
     *
     * @mbggenerated
     */
    public void setStatsId(Integer statsId) {
        this.statsId = statsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.name
     *
     * @return the value of players.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.name
     *
     * @param name the value for players.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.team
     *
     * @return the value of players.team
     *
     * @mbggenerated
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.team
     *
     * @param team the value for players.team
     *
     * @mbggenerated
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.contract
     *
     * @return the value of players.contract
     *
     * @mbggenerated
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.contract
     *
     * @param contract the value for players.contract
     *
     * @mbggenerated
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players.position
     *
     * @return the value of players.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players.position
     *
     * @param position the value for players.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Players other = (Players) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSalary() == null ? other.getSalary() == null : this.getSalary().equals(other.getSalary()))
            && (this.getInfoId() == null ? other.getInfoId() == null : this.getInfoId().equals(other.getInfoId()))
            && (this.getStatsId() == null ? other.getStatsId() == null : this.getStatsId().equals(other.getStatsId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTeam() == null ? other.getTeam() == null : this.getTeam().equals(other.getTeam()))
            && (this.getContract() == null ? other.getContract() == null : this.getContract().equals(other.getContract()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSalary() == null) ? 0 : getSalary().hashCode());
        result = prime * result + ((getInfoId() == null) ? 0 : getInfoId().hashCode());
        result = prime * result + ((getStatsId() == null) ? 0 : getStatsId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTeam() == null) ? 0 : getTeam().hashCode());
        result = prime * result + ((getContract() == null) ? 0 : getContract().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", salary=").append(salary);
        sb.append(", infoId=").append(infoId);
        sb.append(", statsId=").append(statsId);
        sb.append(", name=").append(name);
        sb.append(", team=").append(team);
        sb.append(", contract=").append(contract);
        sb.append(", position=").append(position);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}