package com.cn.ssm.entity;

import java.io.Serializable;

public class Players_Stats implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.gtime
     *
     * @mbggenerated
     */
    private Integer gtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.point
     *
     * @mbggenerated
     */
    private Double point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.rebound
     *
     * @mbggenerated
     */
    private Double rebound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.assist
     *
     * @mbggenerated
     */
    private Double assist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.steal
     *
     * @mbggenerated
     */
    private Double steal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.block
     *
     * @mbggenerated
     */
    private Double block;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.ato
     *
     * @mbggenerated
     */
    private Double ato;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.shot
     *
     * @mbggenerated
     */
    private Double shot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.shotRate
     *
     * @mbggenerated
     */
    private Double shotrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.threeShot
     *
     * @mbggenerated
     */
    private Double threeshot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.threeRate
     *
     * @mbggenerated
     */
    private Double threerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.freeShot
     *
     * @mbggenerated
     */
    private Double freeshot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.freeRate
     *
     * @mbggenerated
     */
    private Double freerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.efg
     *
     * @mbggenerated
     */
    private Double efg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.TS
     *
     * @mbggenerated
     */
    private Double ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.offRtg
     *
     * @mbggenerated
     */
    private Double offrtg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.defRtg
     *
     * @mbggenerated
     */
    private Double defrtg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_stats.per
     *
     * @mbggenerated
     */
    private Double per;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table players_stats
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.ID
     *
     * @return the value of players_stats.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.ID
     *
     * @param id the value for players_stats.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.gtime
     *
     * @return the value of players_stats.gtime
     *
     * @mbggenerated
     */
    public Integer getGtime() {
        return gtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.gtime
     *
     * @param gtime the value for players_stats.gtime
     *
     * @mbggenerated
     */
    public void setGtime(Integer gtime) {
        this.gtime = gtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.point
     *
     * @return the value of players_stats.point
     *
     * @mbggenerated
     */
    public Double getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.point
     *
     * @param point the value for players_stats.point
     *
     * @mbggenerated
     */
    public void setPoint(Double point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.rebound
     *
     * @return the value of players_stats.rebound
     *
     * @mbggenerated
     */
    public Double getRebound() {
        return rebound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.rebound
     *
     * @param rebound the value for players_stats.rebound
     *
     * @mbggenerated
     */
    public void setRebound(Double rebound) {
        this.rebound = rebound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.assist
     *
     * @return the value of players_stats.assist
     *
     * @mbggenerated
     */
    public Double getAssist() {
        return assist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.assist
     *
     * @param assist the value for players_stats.assist
     *
     * @mbggenerated
     */
    public void setAssist(Double assist) {
        this.assist = assist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.steal
     *
     * @return the value of players_stats.steal
     *
     * @mbggenerated
     */
    public Double getSteal() {
        return steal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.steal
     *
     * @param steal the value for players_stats.steal
     *
     * @mbggenerated
     */
    public void setSteal(Double steal) {
        this.steal = steal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.block
     *
     * @return the value of players_stats.block
     *
     * @mbggenerated
     */
    public Double getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.block
     *
     * @param block the value for players_stats.block
     *
     * @mbggenerated
     */
    public void setBlock(Double block) {
        this.block = block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.ato
     *
     * @return the value of players_stats.ato
     *
     * @mbggenerated
     */
    public Double getAto() {
        return ato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.ato
     *
     * @param ato the value for players_stats.ato
     *
     * @mbggenerated
     */
    public void setAto(Double ato) {
        this.ato = ato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.shot
     *
     * @return the value of players_stats.shot
     *
     * @mbggenerated
     */
    public Double getShot() {
        return shot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.shot
     *
     * @param shot the value for players_stats.shot
     *
     * @mbggenerated
     */
    public void setShot(Double shot) {
        this.shot = shot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.shotRate
     *
     * @return the value of players_stats.shotRate
     *
     * @mbggenerated
     */
    public Double getShotrate() {
        return shotrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.shotRate
     *
     * @param shotrate the value for players_stats.shotRate
     *
     * @mbggenerated
     */
    public void setShotrate(Double shotrate) {
        this.shotrate = shotrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.threeShot
     *
     * @return the value of players_stats.threeShot
     *
     * @mbggenerated
     */
    public Double getThreeshot() {
        return threeshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.threeShot
     *
     * @param threeshot the value for players_stats.threeShot
     *
     * @mbggenerated
     */
    public void setThreeshot(Double threeshot) {
        this.threeshot = threeshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.threeRate
     *
     * @return the value of players_stats.threeRate
     *
     * @mbggenerated
     */
    public Double getThreerate() {
        return threerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.threeRate
     *
     * @param threerate the value for players_stats.threeRate
     *
     * @mbggenerated
     */
    public void setThreerate(Double threerate) {
        this.threerate = threerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.freeShot
     *
     * @return the value of players_stats.freeShot
     *
     * @mbggenerated
     */
    public Double getFreeshot() {
        return freeshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.freeShot
     *
     * @param freeshot the value for players_stats.freeShot
     *
     * @mbggenerated
     */
    public void setFreeshot(Double freeshot) {
        this.freeshot = freeshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.freeRate
     *
     * @return the value of players_stats.freeRate
     *
     * @mbggenerated
     */
    public Double getFreerate() {
        return freerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.freeRate
     *
     * @param freerate the value for players_stats.freeRate
     *
     * @mbggenerated
     */
    public void setFreerate(Double freerate) {
        this.freerate = freerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.efg
     *
     * @return the value of players_stats.efg
     *
     * @mbggenerated
     */
    public Double getEfg() {
        return efg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.efg
     *
     * @param efg the value for players_stats.efg
     *
     * @mbggenerated
     */
    public void setEfg(Double efg) {
        this.efg = efg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.TS
     *
     * @return the value of players_stats.TS
     *
     * @mbggenerated
     */
    public Double getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.TS
     *
     * @param ts the value for players_stats.TS
     *
     * @mbggenerated
     */
    public void setTs(Double ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.offRtg
     *
     * @return the value of players_stats.offRtg
     *
     * @mbggenerated
     */
    public Double getOffrtg() {
        return offrtg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.offRtg
     *
     * @param offrtg the value for players_stats.offRtg
     *
     * @mbggenerated
     */
    public void setOffrtg(Double offrtg) {
        this.offrtg = offrtg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.defRtg
     *
     * @return the value of players_stats.defRtg
     *
     * @mbggenerated
     */
    public Double getDefrtg() {
        return defrtg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.defRtg
     *
     * @param defrtg the value for players_stats.defRtg
     *
     * @mbggenerated
     */
    public void setDefrtg(Double defrtg) {
        this.defrtg = defrtg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_stats.per
     *
     * @return the value of players_stats.per
     *
     * @mbggenerated
     */
    public Double getPer() {
        return per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_stats.per
     *
     * @param per the value for players_stats.per
     *
     * @mbggenerated
     */
    public void setPer(Double per) {
        this.per = per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_stats
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Players_Stats other = (Players_Stats) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGtime() == null ? other.getGtime() == null : this.getGtime().equals(other.getGtime()))
            && (this.getPoint() == null ? other.getPoint() == null : this.getPoint().equals(other.getPoint()))
            && (this.getRebound() == null ? other.getRebound() == null : this.getRebound().equals(other.getRebound()))
            && (this.getAssist() == null ? other.getAssist() == null : this.getAssist().equals(other.getAssist()))
            && (this.getSteal() == null ? other.getSteal() == null : this.getSteal().equals(other.getSteal()))
            && (this.getBlock() == null ? other.getBlock() == null : this.getBlock().equals(other.getBlock()))
            && (this.getAto() == null ? other.getAto() == null : this.getAto().equals(other.getAto()))
            && (this.getShot() == null ? other.getShot() == null : this.getShot().equals(other.getShot()))
            && (this.getShotrate() == null ? other.getShotrate() == null : this.getShotrate().equals(other.getShotrate()))
            && (this.getThreeshot() == null ? other.getThreeshot() == null : this.getThreeshot().equals(other.getThreeshot()))
            && (this.getThreerate() == null ? other.getThreerate() == null : this.getThreerate().equals(other.getThreerate()))
            && (this.getFreeshot() == null ? other.getFreeshot() == null : this.getFreeshot().equals(other.getFreeshot()))
            && (this.getFreerate() == null ? other.getFreerate() == null : this.getFreerate().equals(other.getFreerate()))
            && (this.getEfg() == null ? other.getEfg() == null : this.getEfg().equals(other.getEfg()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()))
            && (this.getOffrtg() == null ? other.getOffrtg() == null : this.getOffrtg().equals(other.getOffrtg()))
            && (this.getDefrtg() == null ? other.getDefrtg() == null : this.getDefrtg().equals(other.getDefrtg()))
            && (this.getPer() == null ? other.getPer() == null : this.getPer().equals(other.getPer()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_stats
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGtime() == null) ? 0 : getGtime().hashCode());
        result = prime * result + ((getPoint() == null) ? 0 : getPoint().hashCode());
        result = prime * result + ((getRebound() == null) ? 0 : getRebound().hashCode());
        result = prime * result + ((getAssist() == null) ? 0 : getAssist().hashCode());
        result = prime * result + ((getSteal() == null) ? 0 : getSteal().hashCode());
        result = prime * result + ((getBlock() == null) ? 0 : getBlock().hashCode());
        result = prime * result + ((getAto() == null) ? 0 : getAto().hashCode());
        result = prime * result + ((getShot() == null) ? 0 : getShot().hashCode());
        result = prime * result + ((getShotrate() == null) ? 0 : getShotrate().hashCode());
        result = prime * result + ((getThreeshot() == null) ? 0 : getThreeshot().hashCode());
        result = prime * result + ((getThreerate() == null) ? 0 : getThreerate().hashCode());
        result = prime * result + ((getFreeshot() == null) ? 0 : getFreeshot().hashCode());
        result = prime * result + ((getFreerate() == null) ? 0 : getFreerate().hashCode());
        result = prime * result + ((getEfg() == null) ? 0 : getEfg().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        result = prime * result + ((getOffrtg() == null) ? 0 : getOffrtg().hashCode());
        result = prime * result + ((getDefrtg() == null) ? 0 : getDefrtg().hashCode());
        result = prime * result + ((getPer() == null) ? 0 : getPer().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_stats
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gtime=").append(gtime);
        sb.append(", point=").append(point);
        sb.append(", rebound=").append(rebound);
        sb.append(", assist=").append(assist);
        sb.append(", steal=").append(steal);
        sb.append(", block=").append(block);
        sb.append(", ato=").append(ato);
        sb.append(", shot=").append(shot);
        sb.append(", shotrate=").append(shotrate);
        sb.append(", threeshot=").append(threeshot);
        sb.append(", threerate=").append(threerate);
        sb.append(", freeshot=").append(freeshot);
        sb.append(", freerate=").append(freerate);
        sb.append(", efg=").append(efg);
        sb.append(", ts=").append(ts);
        sb.append(", offrtg=").append(offrtg);
        sb.append(", defrtg=").append(defrtg);
        sb.append(", per=").append(per);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}