package com.cn.ssm.entity;

import java.io.Serializable;
import java.util.Date;

public class PlayersInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.birth
     *
     * @mbggenerated
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.draft
     *
     * @mbggenerated
     */
    private String draft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.height
     *
     * @mbggenerated
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.weight
     *
     * @mbggenerated
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.arms
     *
     * @mbggenerated
     */
    private Double arms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column players_info.stand_tall
     *
     * @mbggenerated
     */
    private Double standTall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table players_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.id
     *
     * @return the value of players_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.id
     *
     * @param id the value for players_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.birth
     *
     * @return the value of players_info.birth
     *
     * @mbggenerated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.birth
     *
     * @param birth the value for players_info.birth
     *
     * @mbggenerated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.nation
     *
     * @return the value of players_info.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.nation
     *
     * @param nation the value for players_info.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.draft
     *
     * @return the value of players_info.draft
     *
     * @mbggenerated
     */
    public String getDraft() {
        return draft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.draft
     *
     * @param draft the value for players_info.draft
     *
     * @mbggenerated
     */
    public void setDraft(String draft) {
        this.draft = draft == null ? null : draft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.height
     *
     * @return the value of players_info.height
     *
     * @mbggenerated
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.height
     *
     * @param height the value for players_info.height
     *
     * @mbggenerated
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.weight
     *
     * @return the value of players_info.weight
     *
     * @mbggenerated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.weight
     *
     * @param weight the value for players_info.weight
     *
     * @mbggenerated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.arms
     *
     * @return the value of players_info.arms
     *
     * @mbggenerated
     */
    public Double getArms() {
        return arms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.arms
     *
     * @param arms the value for players_info.arms
     *
     * @mbggenerated
     */
    public void setArms(Double arms) {
        this.arms = arms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column players_info.stand_tall
     *
     * @return the value of players_info.stand_tall
     *
     * @mbggenerated
     */
    public Double getStandTall() {
        return standTall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column players_info.stand_tall
     *
     * @param standTall the value for players_info.stand_tall
     *
     * @mbggenerated
     */
    public void setStandTall(Double standTall) {
        this.standTall = standTall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PlayersInfo other = (PlayersInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBirth() == null ? other.getBirth() == null : this.getBirth().equals(other.getBirth()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getDraft() == null ? other.getDraft() == null : this.getDraft().equals(other.getDraft()))
            && (this.getHeight() == null ? other.getHeight() == null : this.getHeight().equals(other.getHeight()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getArms() == null ? other.getArms() == null : this.getArms().equals(other.getArms()))
            && (this.getStandTall() == null ? other.getStandTall() == null : this.getStandTall().equals(other.getStandTall()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBirth() == null) ? 0 : getBirth().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getDraft() == null) ? 0 : getDraft().hashCode());
        result = prime * result + ((getHeight() == null) ? 0 : getHeight().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getArms() == null) ? 0 : getArms().hashCode());
        result = prime * result + ((getStandTall() == null) ? 0 : getStandTall().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", birth=").append(birth);
        sb.append(", nation=").append(nation);
        sb.append(", draft=").append(draft);
        sb.append(", height=").append(height);
        sb.append(", weight=").append(weight);
        sb.append(", arms=").append(arms);
        sb.append(", standTall=").append(standTall);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}