package com.cn.ssm.entity;

import java.io.Serializable;

public class Records implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.user1_id
     *
     * @mbggenerated
     */
    private Integer user1Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.user2_id
     *
     * @mbggenerated
     */
    private Integer user2Id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.id
     *
     * @return the value of records.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.id
     *
     * @param id the value for records.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.user1_id
     *
     * @return the value of records.user1_id
     *
     * @mbggenerated
     */
    public Integer getUser1Id() {
        return user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.user1_id
     *
     * @param user1Id the value for records.user1_id
     *
     * @mbggenerated
     */
    public void setUser1Id(Integer user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.user2_id
     *
     * @return the value of records.user2_id
     *
     * @mbggenerated
     */
    public Integer getUser2Id() {
        return user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.user2_id
     *
     * @param user2Id the value for records.user2_id
     *
     * @mbggenerated
     */
    public void setUser2Id(Integer user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.result
     *
     * @return the value of records.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.result
     *
     * @param result the value for records.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Records other = (Records) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUser1Id() == null ? other.getUser1Id() == null : this.getUser1Id().equals(other.getUser1Id()))
            && (this.getUser2Id() == null ? other.getUser2Id() == null : this.getUser2Id().equals(other.getUser2Id()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUser1Id() == null) ? 0 : getUser1Id().hashCode());
        result = prime * result + ((getUser2Id() == null) ? 0 : getUser2Id().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", user1Id=").append(user1Id);
        sb.append(", user2Id=").append(user2Id);
        sb.append(", result=").append(result);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}