package com.cn.ssm.entity;

import java.io.Serializable;

public class Setting implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.quality
     *
     * @mbggenerated
     */
    private Integer quality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.music
     *
     * @mbggenerated
     */
    private Boolean music;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setting.noyice
     *
     * @mbggenerated
     */
    private Boolean noyice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table setting
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.ID
     *
     * @return the value of setting.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.ID
     *
     * @param id the value for setting.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.quality
     *
     * @return the value of setting.quality
     *
     * @mbggenerated
     */
    public Integer getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.quality
     *
     * @param quality the value for setting.quality
     *
     * @mbggenerated
     */
    public void setQuality(Integer quality) {
        this.quality = quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.music
     *
     * @return the value of setting.music
     *
     * @mbggenerated
     */
    public Boolean getMusic() {
        return music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.music
     *
     * @param music the value for setting.music
     *
     * @mbggenerated
     */
    public void setMusic(Boolean music) {
        this.music = music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setting.noyice
     *
     * @return the value of setting.noyice
     *
     * @mbggenerated
     */
    public Boolean getNoyice() {
        return noyice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setting.noyice
     *
     * @param noyice the value for setting.noyice
     *
     * @mbggenerated
     */
    public void setNoyice(Boolean noyice) {
        this.noyice = noyice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Setting other = (Setting) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuality() == null ? other.getQuality() == null : this.getQuality().equals(other.getQuality()))
            && (this.getMusic() == null ? other.getMusic() == null : this.getMusic().equals(other.getMusic()))
            && (this.getNoyice() == null ? other.getNoyice() == null : this.getNoyice().equals(other.getNoyice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuality() == null) ? 0 : getQuality().hashCode());
        result = prime * result + ((getMusic() == null) ? 0 : getMusic().hashCode());
        result = prime * result + ((getNoyice() == null) ? 0 : getNoyice().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", quality=").append(quality);
        sb.append(", music=").append(music);
        sb.append(", noyice=").append(noyice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}