package com.cn.ssm.entity;

import java.io.Serializable;

public class User_Info implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_Info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_Info.belongTeam
     *
     * @mbggenerated
     */
    private Integer belongteam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_Info.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_Info.VIP
     *
     * @mbggenerated
     */
    private Integer vip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_Info.user_id
     *
     * @return the value of user_Info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_Info.user_id
     *
     * @param userId the value for user_Info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_Info.belongTeam
     *
     * @return the value of user_Info.belongTeam
     *
     * @mbggenerated
     */
    public Integer getBelongteam() {
        return belongteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_Info.belongTeam
     *
     * @param belongteam the value for user_Info.belongTeam
     *
     * @mbggenerated
     */
    public void setBelongteam(Integer belongteam) {
        this.belongteam = belongteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_Info.level
     *
     * @return the value of user_Info.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_Info.level
     *
     * @param level the value for user_Info.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_Info.VIP
     *
     * @return the value of user_Info.VIP
     *
     * @mbggenerated
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_Info.VIP
     *
     * @param vip the value for user_Info.VIP
     *
     * @mbggenerated
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User_Info other = (User_Info) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBelongteam() == null ? other.getBelongteam() == null : this.getBelongteam().equals(other.getBelongteam()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getVip() == null ? other.getVip() == null : this.getVip().equals(other.getVip()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBelongteam() == null) ? 0 : getBelongteam().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getVip() == null) ? 0 : getVip().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", belongteam=").append(belongteam);
        sb.append(", level=").append(level);
        sb.append(", vip=").append(vip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}