package com.cn.ssm.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userinfo
     *
     * @mbggenerated
     */
    private Integer userinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.setting
     *
     * @mbggenerated
     */
    private Integer setting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.power
     *
     * @mbggenerated
     */
    private Integer power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.friends_num
     *
     * @mbggenerated
     */
    private Integer friendsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.package_num
     *
     * @mbggenerated
     */
    private Integer packageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userinfo
     *
     * @return the value of user.userinfo
     *
     * @mbggenerated
     */
    public Integer getUserinfo() {
        return userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userinfo
     *
     * @param userinfo the value for user.userinfo
     *
     * @mbggenerated
     */
    public void setUserinfo(Integer userinfo) {
        this.userinfo = userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.setting
     *
     * @return the value of user.setting
     *
     * @mbggenerated
     */
    public Integer getSetting() {
        return setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.setting
     *
     * @param setting the value for user.setting
     *
     * @mbggenerated
     */
    public void setSetting(Integer setting) {
        this.setting = setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.power
     *
     * @return the value of user.power
     *
     * @mbggenerated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.power
     *
     * @param power the value for user.power
     *
     * @mbggenerated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.money
     *
     * @return the value of user.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.money
     *
     * @param money the value for user.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.friends_num
     *
     * @return the value of user.friends_num
     *
     * @mbggenerated
     */
    public Integer getFriendsNum() {
        return friendsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.friends_num
     *
     * @param friendsNum the value for user.friends_num
     *
     * @mbggenerated
     */
    public void setFriendsNum(Integer friendsNum) {
        this.friendsNum = friendsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.package_num
     *
     * @return the value of user.package_num
     *
     * @mbggenerated
     */
    public Integer getPackageNum() {
        return packageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.package_num
     *
     * @param packageNum the value for user.package_num
     *
     * @mbggenerated
     */
    public void setPackageNum(Integer packageNum) {
        this.packageNum = packageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserinfo() == null ? other.getUserinfo() == null : this.getUserinfo().equals(other.getUserinfo()))
            && (this.getSetting() == null ? other.getSetting() == null : this.getSetting().equals(other.getSetting()))
            && (this.getPower() == null ? other.getPower() == null : this.getPower().equals(other.getPower()))
            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
            && (this.getFriendsNum() == null ? other.getFriendsNum() == null : this.getFriendsNum().equals(other.getFriendsNum()))
            && (this.getPackageNum() == null ? other.getPackageNum() == null : this.getPackageNum().equals(other.getPackageNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserinfo() == null) ? 0 : getUserinfo().hashCode());
        result = prime * result + ((getSetting() == null) ? 0 : getSetting().hashCode());
        result = prime * result + ((getPower() == null) ? 0 : getPower().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getFriendsNum() == null) ? 0 : getFriendsNum().hashCode());
        result = prime * result + ((getPackageNum() == null) ? 0 : getPackageNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userinfo=").append(userinfo);
        sb.append(", setting=").append(setting);
        sb.append(", power=").append(power);
        sb.append(", money=").append(money);
        sb.append(", friendsNum=").append(friendsNum);
        sb.append(", packageNum=").append(packageNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}