package entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userinfo
     *
     * @mbggenerated
     */
    private Integer userinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.setting
     *
     * @mbggenerated
     */
    private Integer setting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.power
     *
     * @mbggenerated
     */
    private Integer power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.money
     *
     * @mbggenerated
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.friends_num
     *
     * @mbggenerated
     */
    private Integer friendsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.package_id
     *
     * @mbggenerated
     */
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.O_tactics
     *
     * @mbggenerated
     */
    private Integer oTactics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.D_tactics
     *
     * @mbggenerated
     */
    private Integer dTactics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loginStatus
     *
     * @mbggenerated
     */
    private Integer loginstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userinfo
     *
     * @return the value of user.userinfo
     *
     * @mbggenerated
     */
    public Integer getUserinfo() {
        return userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userinfo
     *
     * @param userinfo the value for user.userinfo
     *
     * @mbggenerated
     */
    public void setUserinfo(Integer userinfo) {
        this.userinfo = userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.setting
     *
     * @return the value of user.setting
     *
     * @mbggenerated
     */
    public Integer getSetting() {
        return setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.setting
     *
     * @param setting the value for user.setting
     *
     * @mbggenerated
     */
    public void setSetting(Integer setting) {
        this.setting = setting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.power
     *
     * @return the value of user.power
     *
     * @mbggenerated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.power
     *
     * @param power the value for user.power
     *
     * @mbggenerated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.money
     *
     * @return the value of user.money
     *
     * @mbggenerated
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.money
     *
     * @param money the value for user.money
     *
     * @mbggenerated
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.friends_num
     *
     * @return the value of user.friends_num
     *
     * @mbggenerated
     */
    public Integer getFriendsNum() {
        return friendsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.friends_num
     *
     * @param friendsNum the value for user.friends_num
     *
     * @mbggenerated
     */
    public void setFriendsNum(Integer friendsNum) {
        this.friendsNum = friendsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.package_id
     *
     * @return the value of user.package_id
     *
     * @mbggenerated
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.package_id
     *
     * @param packageId the value for user.package_id
     *
     * @mbggenerated
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.O_tactics
     *
     * @return the value of user.O_tactics
     *
     * @mbggenerated
     */
    public Integer getoTactics() {
        return oTactics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.O_tactics
     *
     * @param oTactics the value for user.O_tactics
     *
     * @mbggenerated
     */
    public void setoTactics(Integer oTactics) {
        this.oTactics = oTactics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.D_tactics
     *
     * @return the value of user.D_tactics
     *
     * @mbggenerated
     */
    public Integer getdTactics() {
        return dTactics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.D_tactics
     *
     * @param dTactics the value for user.D_tactics
     *
     * @mbggenerated
     */
    public void setdTactics(Integer dTactics) {
        this.dTactics = dTactics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loginStatus
     *
     * @return the value of user.loginStatus
     *
     * @mbggenerated
     */
    public Integer getLoginstatus() {
        return loginstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loginStatus
     *
     * @param loginstatus the value for user.loginStatus
     *
     * @mbggenerated
     */
    public void setLoginstatus(Integer loginstatus) {
        this.loginstatus = loginstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserinfo() == null ? other.getUserinfo() == null : this.getUserinfo().equals(other.getUserinfo()))
            && (this.getSetting() == null ? other.getSetting() == null : this.getSetting().equals(other.getSetting()))
            && (this.getPower() == null ? other.getPower() == null : this.getPower().equals(other.getPower()))
            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
            && (this.getFriendsNum() == null ? other.getFriendsNum() == null : this.getFriendsNum().equals(other.getFriendsNum()))
            && (this.getPackageId() == null ? other.getPackageId() == null : this.getPackageId().equals(other.getPackageId()))
            && (this.getoTactics() == null ? other.getoTactics() == null : this.getoTactics().equals(other.getoTactics()))
            && (this.getdTactics() == null ? other.getdTactics() == null : this.getdTactics().equals(other.getdTactics()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getLoginstatus() == null ? other.getLoginstatus() == null : this.getLoginstatus().equals(other.getLoginstatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserinfo() == null) ? 0 : getUserinfo().hashCode());
        result = prime * result + ((getSetting() == null) ? 0 : getSetting().hashCode());
        result = prime * result + ((getPower() == null) ? 0 : getPower().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getFriendsNum() == null) ? 0 : getFriendsNum().hashCode());
        result = prime * result + ((getPackageId() == null) ? 0 : getPackageId().hashCode());
        result = prime * result + ((getoTactics() == null) ? 0 : getoTactics().hashCode());
        result = prime * result + ((getdTactics() == null) ? 0 : getdTactics().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getLoginstatus() == null) ? 0 : getLoginstatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userinfo=").append(userinfo);
        sb.append(", setting=").append(setting);
        sb.append(", power=").append(power);
        sb.append(", money=").append(money);
        sb.append(", friendsNum=").append(friendsNum);
        sb.append(", packageId=").append(packageId);
        sb.append(", oTactics=").append(oTactics);
        sb.append(", dTactics=").append(dTactics);
        sb.append(", username=").append(username);
        sb.append(", loginstatus=").append(loginstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}