package entity;

import java.io.Serializable;

public class BelongTeam implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belongTeam.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belongTeam.players_num
     *
     * @mbggenerated
     */
    private Integer playersNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belongTeam.members
     *
     * @mbggenerated
     */
    private Integer members;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belongTeam.lineup
     *
     * @mbggenerated
     */
    private Integer lineup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belongTeam.ID
     *
     * @return the value of belongTeam.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belongTeam.ID
     *
     * @param id the value for belongTeam.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belongTeam.players_num
     *
     * @return the value of belongTeam.players_num
     *
     * @mbggenerated
     */
    public Integer getPlayersNum() {
        return playersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belongTeam.players_num
     *
     * @param playersNum the value for belongTeam.players_num
     *
     * @mbggenerated
     */
    public void setPlayersNum(Integer playersNum) {
        this.playersNum = playersNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belongTeam.members
     *
     * @return the value of belongTeam.members
     *
     * @mbggenerated
     */
    public Integer getMembers() {
        return members;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belongTeam.members
     *
     * @param members the value for belongTeam.members
     *
     * @mbggenerated
     */
    public void setMembers(Integer members) {
        this.members = members;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belongTeam.lineup
     *
     * @return the value of belongTeam.lineup
     *
     * @mbggenerated
     */
    public Integer getLineup() {
        return lineup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belongTeam.lineup
     *
     * @param lineup the value for belongTeam.lineup
     *
     * @mbggenerated
     */
    public void setLineup(Integer lineup) {
        this.lineup = lineup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BelongTeam other = (BelongTeam) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPlayersNum() == null ? other.getPlayersNum() == null : this.getPlayersNum().equals(other.getPlayersNum()))
            && (this.getMembers() == null ? other.getMembers() == null : this.getMembers().equals(other.getMembers()))
            && (this.getLineup() == null ? other.getLineup() == null : this.getLineup().equals(other.getLineup()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPlayersNum() == null) ? 0 : getPlayersNum().hashCode());
        result = prime * result + ((getMembers() == null) ? 0 : getMembers().hashCode());
        result = prime * result + ((getLineup() == null) ? 0 : getLineup().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", playersNum=").append(playersNum);
        sb.append(", members=").append(members);
        sb.append(", lineup=").append(lineup);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}