package com.cn.ssm.dao;

import com.cn.ssm.entity.APPToken;

public interface APPTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int insert(APPToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int insertSelective(APPToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    APPToken selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(APPToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptoken
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(APPToken record);
}