package com.cn.ssm.dao;

import com.cn.ssm.entity.BelongTeam;

public interface BelongTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    int insert(BelongTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    int insertSelective(BelongTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    BelongTeam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BelongTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongTeam
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BelongTeam record);
}