package com.cn.ssm.dao;

import com.cn.ssm.entity.Consumables;

public interface ConsumablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    int insert(Consumables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    int insertSelective(Consumables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    Consumables selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Consumables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumables
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Consumables record);
    
    //自定义方法
    int insert_AI(Consumables record);
    
    Consumables selectByuserId_recordId(int id,int goods_id);
}