package com.cn.ssm.dao;

import java.util.ArrayList;
import java.util.List;

import com.cn.ssm.entity.Friends;

public interface FriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int insert(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int insertSelective(Friends record);
    
    ArrayList<Integer> selectByUser_ID(int user_ID1);
    
    Friends selectByUser_IDs(int user_ID,int usr_ID2);
    
    int update(Friends record);
}