package com.cn.ssm.dao;

import com.cn.ssm.entity.Lineup;

public interface LineupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineup
     *
     * @mbggenerated
     */
    int insert(Lineup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineup
     *
     * @mbggenerated
     */
    int insertSelective(Lineup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineup
     *
     * @mbggenerated
     */
    Lineup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lineup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lineup record);
    
   
}