package com.cn.ssm.dao;

import java.util.List;

import com.cn.ssm.entity.matching;

public interface matchingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matching
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matching
     *
     * @mbggenerated
     */
    int insert(matching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matching
     *
     * @mbggenerated
     */
    int insertSelective(matching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matching
     *
     * @mbggenerated
     */
    matching selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matching
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(matching record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matching
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(matching record);
    
    List<matching> getMatching(int level);
    
    public int getMaxId();
}