package com.cn.ssm.dao;

import com.cn.ssm.entity.Package;

public interface PackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    int insert(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    int insertSelective(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    Package selectByPrimaryKey(Integer packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Package record);
    //自定义方法
    Package selectByUserID_goodsid(int userID,int goodsid); //查询用户名下仓库中是否存在该类物品
    int insertfrag_autoIncrement(Package record);//按主键自增方式插入记录
    int insert_autoIncrement(Package record);//按主键自增方式把球员拆成碎片插入记录

}