package com.cn.ssm.dao;

import com.cn.ssm.entity.PhoneLogin;

public interface PhoneLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneLogin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneLogin
     *
     * @mbggenerated
     */
    int insert(PhoneLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneLogin
     *
     * @mbggenerated
     */
    int insertSelective(PhoneLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneLogin
     *
     * @mbggenerated
     */
    PhoneLogin selectByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneLogin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoneLogin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneLogin record);
}