package com.cn.ssm.dao;

import com.cn.ssm.entity.Players_Info;

public interface Players_InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int insert(Players_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int insertSelective(Players_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    Players_Info selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Players_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Players_Info record);
}