package com.cn.ssm.dao;

import com.cn.ssm.entity.PlayersInfo;

public interface PlayersInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int insert(PlayersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int insertSelective(PlayersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    PlayersInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlayersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlayersInfo record);
}