package com.cn.ssm.dao;

import java.util.List;

import com.cn.ssm.entity.Goods;
import com.cn.ssm.entity.Players;

public interface PlayersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    int insert(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    int insertSelective(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    Players selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Players record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table players
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Players record);
	 List<Players> selectDirPlayers();  //鍙栧嚭鐣岄潰榛樿鏄剧ず鐨勭悆鍛�
	 List<Players> selectByPosition(String position);  //鍙栧嚭婊¤冻鐢ㄦ埛鎸変綅缃畾鍚戞嫑鍕熺殑鐞冨憳
	 List<Players> selectByScore();  //鍙栧嚭婊¤冻鐢ㄦ埛鎸夎瘎鍒嗗畾鍚戞嫑鍕熺殑鐞冨憳
	 List<Players> selectBySalary();  //鍙栧嚭婊¤冻鐢ㄦ埛鎸夎柂璧勫畾鍚戞嫑鍕熺殑鐞冨憳
	 Players selectByName(String name);
}