package com.cn.ssm.dao;

import com.cn.ssm.entity.Records;

public interface RecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int insert(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int insertSelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    Records selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Records record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Records record);
    
    Records selectByUserId(Integer id);
    Records selectByUserId2(Integer id);
}