package com.cn.ssm.dao;

import com.cn.ssm.entity.TeamMembers;

public interface TeamMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamMembers
     *
     * @mbggenerated
     */
    int insert(TeamMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamMembers
     *
     * @mbggenerated
     */
    int insertSelective(TeamMembers record);
	TeamMembers selectByUserID_playerid(Integer userId,Integer playerId);  //自定义
}