package com.cn.ssm.dao;

import com.cn.ssm.entity.User_Info;

public interface User_InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    int insert(User_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    int insertSelective(User_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    User_Info selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_Info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User_Info record);
}