package com.cn.ssm.dao;

import com.cn.ssm.entity.VIPInfo;

public interface VIPInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vipLevel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP_info
     *
     * @mbggenerated
     */
    int insert(VIPInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP_info
     *
     * @mbggenerated
     */
    int insertSelective(VIPInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP_info
     *
     * @mbggenerated
     */
    VIPInfo selectByPrimaryKey(Integer vipLevel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VIPInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIP_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VIPInfo record);
}